name: ItemsWeaver
version: 1.0.0
main: com.codylamer.itemsweaver.ItemsWeaver
api-version: 1.13
depend: [Denizen, ItemsAdder]
authors: [CodYLameR]
description: Bridge between ItemsAdder and DenizenScript