name: ItemsWeaver
author: CodYLameR
version: ${version}
main: com.codylamer.itemsweaver.ItemsWeaver
depend: [Denizen, ItemsAdder]
description: Bridge between ItemsAdder and DenizenScript
website: https://github.com/codylamer/ItemsWeaver

api-version: '1.21'